# default device. E.g., if not specifying the target device, it will default to the kitchen.
# Side note: this can be the device name, or the MAC address.
default_device = "kitchen"
[resolution]
# Mappings device names to their corresponding device MAC addresses
my_desk = "40:5B:A4:2F:05:46"
kitchen = "DB:1E:B4:E7:A3:75"

